### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by railty** [Vilijan/NFTMarketplace#3]
Nice work, I learned a lot. A few questions though (please let me know if this is not the right place)

1. Why a contract for each NFT? in solidity this can be done in 1 contract, is it because each account can only have up to 1000 nft?
2. Why a separate escrow account/address? why can't I use the stateful contract address as escrow account?
3. why buyer pay seller directly? shouldn't buyer pay escrow account, escrow account deducts a percentage fee and pay the remaining to seller? 

In general, this is quite different than solidity, I am not sure this is a better design or a workaround due to technical limitation, such as 1000 maximum nft.

Thanks for your time

**Comment by Vilijan** [comment]
Hey @railty, I am glad that you enjoyed the tutorial. I will try to answer your questions to the best of my knowledge! 

I don't have any experience with Solidity, so I couldn't make any comparisons. 

Each NFT on Algorand can be implemented in many ways depending on the purpose it solves. If NFT represents an artwork usually the buyer would not want it to have a clawback address. However, if it solves some other purpose such as a ticket or something else, maybe it is ok to have a clawback address.  

1. The goal of this tutorial was to implement a simple tutorial that describes one possible way for creating an NFTMarketplace. The only reason why I used one contract per NFT and one escrow address per NFT was only that it was the easiest way for me to implement it and explain it. When I wrote this tutorial, a stateful smart contract couldn't act as an escrow address. This functionality was added in AVM 1.0, so now the Smart Contract can hold up to 1000 NFTs and also execute transactions. So the solution can be refactored in this direction, but it still has some limitations. 
2. In this tutorial I decided each NFT to have a separate escrow address that will act as its clawback address. If you want to have a single escrow address, then the logic that validates the transfer of the NFT needs to go in the Stateful Contract. For a hackathon, I developed an NFT ticketing system, that acts as a DEX for NFTs. It uses only one Stateful Smart Contract and one escrow. Each user can make sell offers and buys only through the contract. I haven't written a detailed explanation but you can find the code and some documentation on the following [link](https://github.com/Vilijan/Tokility).
3. This comes down to the implementation logic and the design decisions. I used the power of Atomic Transfer to directly transfer the funds to the target addresses. The Stateful Smart contract validates the Atomic Transfer, and if the transactions logic is correct, the funds (NFT or Algos) are transferred directly to the target addresses. Some NFT platforms on Algorand use escrow addresses as you mentioned, such as [ALGOxNFT](https://algoxnft.com/listings/live). Others use Atomic Transfers such as [AB2Gallery](https://ab2.gallery/).

If you want to implement an NFT Marketplace where the NFTs do not have a clawback address, you would want to create an escrow address for each NFT that is put on sale(you can try with Stateful Contract but again you are limited to 1000 NFTs). This escrow address will hold the NFT, and the logic about the price and fees. The buyer can take the NFT from the escrow only if he pays the required amount to the seller/platform etc, or the seller can always delete the escrow and take back the NFT.

I hope I didn't miss the point of your questions :)

**Comment by railty** [comment]
This is great, Thanks for the clearification, and thanks for another good resource you mentioned
